#!/bin/bash


# rm -rf dist/*
rm dist/everywhereml-${1}.tar.gz
sed "s/VERSION/${1}/" setup_template.py > setup.py
sed -i '' "s/PACKAGES/$(python enumerate_packages.py)/" setup.py
sed -i '' "s/TEMPLATES/$(python enumerate_templates.py)/" setup.py
python setup.py sdist
twine upload dist/everywhereml-${1}.tar.gz
git add .
git commit -m "bump dist to ${1}"
git push origin master -f
git push origin v$1 -f